theme = "autumn_night"

[editor]
  line-number = "relative"
  auto-pairs = false
  true-color = true
  bufferline = "multiple"

[editor.lsp]
  display-messages = true


[editor.soft-wrap]
  enable = true

[editor.indent-guides]
  render = true
  character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
  skip-levels = 1

[editor.statusline]
  left = ["mode", "spinner"]
  center = ["version-control", "file-base-name"]
  right = ["diagnostics", "selections", "primary-selection-length", "file-encoding", "file-line-ending", "file-type"]
  separator = "│"
  mode.normal = "NORMAL"
  mode.insert = "INSERT"
  mode.select = "SELECT"

# [editor.file-picker]
#   git-ignore=false

[keys.normal]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"
tab="buffer_picker"

[keys.normal.g]
n="goto_next_buffer"
o="goto_line_end"

[keys.normal.space.w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.normal.C-w]
n="jump_view_left"
e="jump_view_down"
E="join_selections"
"A-E"="join_selections_space"

i="jump_view_up"
I="keep_selections"
"A-I"="remove_selections"

o="jump_view_right"


[keys.select]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.z]
e="scroll_down"
i="scroll_up"

[keys.normal.Z]
e="scroll_down"
i="scroll_up"



